AllCops:
    TargetRubyVersion: 2.4
    Exclude:
      - 'lib/steam/client/resources/**/*'
      - 'lib/steam/client/enums/**/*'
Style/FrozenStringLiteralComment:
    Enabled: false
Style/NumericLiterals:
    Enabled: false
